CREATE OR REPLACE VIEW public.project_details AS
 WITH labor_rollup AS (
         SELECT le.po_number,
            round(sum(le.paid_hours), 2) AS hours_to_date,
            round(sum(le.paid_hours * COALESCE(p.specialty_rate, le.hourly_rate)), 2) AS ct_labor_cost_to_date
           FROM labor_entries le
             LEFT JOIN projects p ON p.po_number = le.po_number::text
          WHERE le.po_number IS NOT NULL
          GROUP BY le.po_number
        ), material_rollup AS (
         SELECT qbo_expenses.po_number,
            round(sum(qbo_expenses.amount), 2) AS material_cost_to_date
           FROM qbo_expenses
          WHERE (qbo_expenses.account_name::text = ANY (ARRAY['5020 Direct Supplies'::text, '6250 Direct Supplies:Shop Supplies'::text, 'Direct Supplies'::text, 'Direct Supplies:Shop Supplies'::text])) AND qbo_expenses.po_number IS NOT NULL
          GROUP BY qbo_expenses.po_number
        ), set_rollup AS (
         SELECT qbo_expenses.po_number,
            round(sum(qbo_expenses.amount), 2) AS set_cost_to_date
           FROM qbo_expenses
          WHERE (qbo_expenses.account_name::text = ANY (ARRAY['5040 Sub-Contractors'::text, '5070 Fld Equip, Rent, Repair, Supp'::text, '5080 Job Related Travel'::text, '6230 Fld Equip, Rent, Repair, Supp:Rental Equipment for Job'::text, '6243 Fld Equip, Rent, Repair, Supp:Equipment Repairs'::text, '6303 Job Related Travel:Tolls & Parking'::text, 'Fld Equip, Rent, Repair, Supp:Rental Equipment for Job'::text, 'Job Related Travel'::text, 'Job Related Travel:Mileage Reimbursement'::text, 'Job Related Travel:Tolls & Parking'::text, 'Sub-Contractors'::text])) AND qbo_expenses.po_number IS NOT NULL
          GROUP BY qbo_expenses.po_number
        ), billing_rollup AS (
         SELECT qbo_invoices.po_number,
            round(sum(qbo_invoices.total_amount), 2) AS amount_billed_to_date,
            count(*) AS invoice_count,
            max(qbo_invoices.invoice_date) AS last_invoice_date,
            round(sum(
                CASE
                    WHEN qbo_invoices.milestone_type::text = 'Deposit'::text THEN qbo_invoices.total_amount
                    ELSE 0::numeric
                END), 2) AS deposit_billed,
            round(sum(
                CASE
                    WHEN qbo_invoices.milestone_type::text = 'Progress'::text THEN qbo_invoices.total_amount
                    ELSE 0::numeric
                END), 2) AS progress_billed,
            round(sum(
                CASE
                    WHEN qbo_invoices.milestone_type::text = 'Final'::text THEN qbo_invoices.total_amount
                    ELSE 0::numeric
                END), 2) AS final_billed,
            count(*) FILTER (WHERE qbo_invoices.milestone_type::text = 'Deposit'::text) AS deposit_count,
            count(*) FILTER (WHERE qbo_invoices.milestone_type::text = 'Progress'::text) AS progress_count,
            count(*) FILTER (WHERE qbo_invoices.milestone_type::text = 'Final'::text) AS final_count
           FROM qbo_invoices
          WHERE qbo_invoices.status::text <> 'Voided'::text AND qbo_invoices.po_number IS NOT NULL
          GROUP BY qbo_invoices.po_number
        ), wip_rollup AS (
         SELECT qbo_journal_entries.po_number,
            round(sum(qbo_journal_entries.amount), 2) AS wip_to_date
           FROM qbo_journal_entries
          WHERE qbo_journal_entries.po_number IS NOT NULL
          GROUP BY qbo_journal_entries.po_number
        ), allocation_rollup AS (
         SELECT ra.po_number,
            count(*) AS allocated_months_count,
            round(sum(ra.allocated_pct), 4) AS allocation_sum_pct,
            round(sum(ra.allocated_amount), 2) AS allocation_sum_amount,
            count(*) FILTER (WHERE ra.is_locked) AS locked_months_count,
            min(ra.period_month) AS first_allocated_month,
            max(ra.period_month) AS last_allocated_month,
            (EXTRACT(year FROM age(max(ra.period_month)::timestamp with time zone, min(ra.period_month)::timestamp with time zone)) * 12::numeric + EXTRACT(month FROM age(max(ra.period_month)::timestamp with time zone, min(ra.period_month)::timestamp with time zone)) + 1::numeric)::integer AS span_months
           FROM revenue_allocations ra
          GROUP BY ra.po_number
        ), base AS (
         SELECT p.po_number,
            p.job_name,
            p.stage,
            p.tracking_mode,
            p.segment,
            p.sales_rep,
            p.team_leader,
            p.project_manager,
            p.job_site_address,
            p.city,
            p.state,
            p.zip_code,
            p.date_job_sold,
            p.estimated_start_date,
            p.duration_days,
            p.estimated_completion_date,
            p.company,
            p.customer,
            p.division_id,
            p.contract_hours,
            p.contract_revenue,
            p.co_hours,
            p.co_revenue,
            p.est_hours_remaining,
            p.est_materials_remaining,
            p.est_set_remaining,
            p.source_attribution,
            p.prev_or_new_customer,
            p.is_closed,
            p.closed_at,
            p.created_at,
            p.updated_at,
            p.hs_object_id,
            p.hubspot_url,
            p.specialty_rate,
            p.prev_wage_rate,
            p.billing_schedule_type,
            p.deposit_pct,
            p.deposit_amount,
            p.deposit_lead_days,
            p.billing_cadence,
            p.billing_notes,
            p.allocation_method,
            p.forecast_labor_cost_override,
            p.forecasted_materials_override,
            p.forecasted_set_override,
            COALESCE(lr.hours_to_date, p.hours_to_date, 0::numeric) AS hours_to_date,
            COALESCE(lr.ct_labor_cost_to_date, 0::numeric) AS ct_labor_cost_to_date,
            p.labor_cost_to_date AS stored_labor_cost,
            COALESCE(mr.material_cost_to_date, p.material_cost_to_date, 0::numeric) AS material_cost_to_date,
            COALESCE(sr.set_cost_to_date, p.set_cost_to_date, 0::numeric) AS set_cost_to_date,
            COALESCE(br.amount_billed_to_date, 0::numeric) AS amount_billed_to_date,
            COALESCE(br.invoice_count, 0::bigint) AS invoice_count,
            br.last_invoice_date,
            COALESCE(br.deposit_billed, 0::numeric) AS deposit_billed,
            COALESCE(br.progress_billed, 0::numeric) AS progress_billed,
            COALESCE(br.final_billed, 0::numeric) AS final_billed,
            COALESCE(br.deposit_count, 0::bigint) AS deposit_count,
            COALESCE(br.progress_count, 0::bigint) AS progress_count,
            COALESCE(br.final_count, 0::bigint) AS final_count,
            COALESCE(wr.wip_to_date, 0::numeric) AS wip_to_date,
            COALESCE(ar.allocated_months_count, 0::bigint) AS allocated_months_count,
            COALESCE(ar.allocation_sum_pct, 0::numeric) AS allocation_sum_pct,
            COALESCE(ar.allocation_sum_amount, 0::numeric) AS allocation_sum_amount,
            COALESCE(ar.locked_months_count, 0::bigint) AS locked_months_count,
            ar.first_allocated_month,
            ar.last_allocated_month,
            COALESCE(ar.span_months, 0) AS span_months,
            d.code AS division_code,
            d.name AS division_name,
            d.avg_wage,
            d.materials_pct,
            d.set_pct,
            bst.display_name AS billing_schedule_display,
            bst.has_deposit AS schedule_has_deposit,
            bst.has_progress AS schedule_has_progress,
            bst.has_wip_accrual AS schedule_has_wip_accrual
           FROM projects p
             LEFT JOIN divisions d ON d.id = p.division_id
             LEFT JOIN billing_schedule_types bst ON bst.code = p.billing_schedule_type
             LEFT JOIN labor_rollup lr ON lr.po_number::text = p.po_number
             LEFT JOIN material_rollup mr ON mr.po_number::text = p.po_number
             LEFT JOIN set_rollup sr ON sr.po_number::text = p.po_number
             LEFT JOIN billing_rollup br ON br.po_number::text = p.po_number
             LEFT JOIN wip_rollup wr ON wr.po_number::text = p.po_number
             LEFT JOIN allocation_rollup ar ON ar.po_number = p.po_number
        ), tier1 AS (
         SELECT b.po_number,
            b.job_name,
            b.stage,
            b.tracking_mode,
            b.segment,
            b.sales_rep,
            b.team_leader,
            b.project_manager,
            b.job_site_address,
            b.city,
            b.state,
            b.zip_code,
            b.date_job_sold,
            b.estimated_start_date,
            b.duration_days,
            b.estimated_completion_date,
            b.company,
            b.customer,
            b.division_id,
            b.contract_hours,
            b.contract_revenue,
            b.co_hours,
            b.co_revenue,
            b.est_hours_remaining,
            b.est_materials_remaining,
            b.est_set_remaining,
            b.source_attribution,
            b.prev_or_new_customer,
            b.is_closed,
            b.closed_at,
            b.created_at,
            b.updated_at,
            b.hs_object_id,
            b.hubspot_url,
            b.specialty_rate,
            b.prev_wage_rate,
            b.billing_schedule_type,
            b.deposit_pct,
            b.deposit_amount,
            b.deposit_lead_days,
            b.billing_cadence,
            b.billing_notes,
            b.allocation_method,
            b.forecast_labor_cost_override,
            b.forecasted_materials_override,
            b.forecasted_set_override,
            b.hours_to_date,
            b.ct_labor_cost_to_date,
            b.stored_labor_cost,
            b.material_cost_to_date,
            b.set_cost_to_date,
            b.amount_billed_to_date,
            b.invoice_count,
            b.last_invoice_date,
            b.deposit_billed,
            b.progress_billed,
            b.final_billed,
            b.deposit_count,
            b.progress_count,
            b.final_count,
            b.wip_to_date,
            b.allocated_months_count,
            b.allocation_sum_pct,
            b.allocation_sum_amount,
            b.locked_months_count,
            b.first_allocated_month,
            b.last_allocated_month,
            b.span_months,
            b.division_code,
            b.division_name,
            b.avg_wage,
            b.materials_pct,
            b.set_pct,
            b.billing_schedule_display,
            b.schedule_has_deposit,
            b.schedule_has_progress,
            b.schedule_has_wip_accrual,
            round(b.contract_revenue / NULLIF(b.contract_hours, 0::numeric), 2) AS contract_sales_rate,
            round(b.co_revenue / NULLIF(b.co_hours, 0::numeric), 2) AS co_sales_rate,
            round(COALESCE(b.contract_hours, 0::numeric) + COALESCE(b.co_hours, 0::numeric), 2) AS total_hours,
            round(COALESCE(b.contract_revenue, 0::numeric) + COALESCE(b.co_revenue, 0::numeric), 2) AS total_revenue,
            round(b.ct_labor_cost_to_date / NULLIF(b.hours_to_date, 0::numeric) * 1.2, 2) AS avg_labor_cost_per_hour
           FROM base b
        ), tier2 AS (
         SELECT t.po_number,
            t.job_name,
            t.stage,
            t.tracking_mode,
            t.segment,
            t.sales_rep,
            t.team_leader,
            t.project_manager,
            t.job_site_address,
            t.city,
            t.state,
            t.zip_code,
            t.date_job_sold,
            t.estimated_start_date,
            t.duration_days,
            t.estimated_completion_date,
            t.company,
            t.customer,
            t.division_id,
            t.contract_hours,
            t.contract_revenue,
            t.co_hours,
            t.co_revenue,
            t.est_hours_remaining,
            t.est_materials_remaining,
            t.est_set_remaining,
            t.source_attribution,
            t.prev_or_new_customer,
            t.is_closed,
            t.closed_at,
            t.created_at,
            t.updated_at,
            t.hs_object_id,
            t.hubspot_url,
            t.specialty_rate,
            t.prev_wage_rate,
            t.billing_schedule_type,
            t.deposit_pct,
            t.deposit_amount,
            t.deposit_lead_days,
            t.billing_cadence,
            t.billing_notes,
            t.allocation_method,
            t.forecast_labor_cost_override,
            t.forecasted_materials_override,
            t.forecasted_set_override,
            t.hours_to_date,
            t.ct_labor_cost_to_date,
            t.stored_labor_cost,
            t.material_cost_to_date,
            t.set_cost_to_date,
            t.amount_billed_to_date,
            t.invoice_count,
            t.last_invoice_date,
            t.deposit_billed,
            t.progress_billed,
            t.final_billed,
            t.deposit_count,
            t.progress_count,
            t.final_count,
            t.wip_to_date,
            t.allocated_months_count,
            t.allocation_sum_pct,
            t.allocation_sum_amount,
            t.locked_months_count,
            t.first_allocated_month,
            t.last_allocated_month,
            t.span_months,
            t.division_code,
            t.division_name,
            t.avg_wage,
            t.materials_pct,
            t.set_pct,
            t.billing_schedule_display,
            t.schedule_has_deposit,
            t.schedule_has_progress,
            t.schedule_has_wip_accrual,
            t.contract_sales_rate,
            t.co_sales_rate,
            t.total_hours,
            t.total_revenue,
            t.avg_labor_cost_per_hour,
            COALESCE(
                CASE
                    WHEN t.specialty_rate IS NOT NULL THEN round(t.specialty_rate * t.hours_to_date * 1.2, 2)
                    WHEN t.prev_wage_rate IS NOT NULL THEN round(t.prev_wage_rate * t.hours_to_date * 1.1127, 2)
                    WHEN t.avg_labor_cost_per_hour > 0::numeric THEN round(t.avg_labor_cost_per_hour * t.hours_to_date, 2)
                    ELSE NULL::numeric
                END, t.stored_labor_cost, 0::numeric) AS labor_cost_to_date,
            COALESCE(
                CASE
                    WHEN t.specialty_rate IS NOT NULL THEN round(t.specialty_rate * COALESCE(t.est_hours_remaining, 0::numeric) * 1.2, 2)
                    WHEN t.prev_wage_rate IS NOT NULL THEN round(t.prev_wage_rate * COALESCE(t.est_hours_remaining, 0::numeric) * 1.1127, 2)
                    ELSE round(t.avg_labor_cost_per_hour * COALESCE(t.est_hours_remaining, 0::numeric), 2)
                END, 0::numeric) AS est_labor_cost_remaining,
            round((COALESCE(t.contract_revenue, 0::numeric) + COALESCE(t.co_revenue, 0::numeric)) / NULLIF(COALESCE(t.contract_hours, 0::numeric) + COALESCE(t.co_hours, 0::numeric), 0::numeric), 2) AS total_sales_rate
           FROM tier1 t
        ), tier2b AS (
         SELECT t.po_number,
            t.job_name,
            t.stage,
            t.tracking_mode,
            t.segment,
            t.sales_rep,
            t.team_leader,
            t.project_manager,
            t.job_site_address,
            t.city,
            t.state,
            t.zip_code,
            t.date_job_sold,
            t.estimated_start_date,
            t.duration_days,
            t.estimated_completion_date,
            t.company,
            t.customer,
            t.division_id,
            t.contract_hours,
            t.contract_revenue,
            t.co_hours,
            t.co_revenue,
            t.est_hours_remaining,
            t.est_materials_remaining,
            t.est_set_remaining,
            t.source_attribution,
            t.prev_or_new_customer,
            t.is_closed,
            t.closed_at,
            t.created_at,
            t.updated_at,
            t.hs_object_id,
            t.hubspot_url,
            t.specialty_rate,
            t.prev_wage_rate,
            t.billing_schedule_type,
            t.deposit_pct,
            t.deposit_amount,
            t.deposit_lead_days,
            t.billing_cadence,
            t.billing_notes,
            t.allocation_method,
            t.hours_to_date,
            t.ct_labor_cost_to_date,
            t.stored_labor_cost,
            t.material_cost_to_date,
            t.set_cost_to_date,
            t.amount_billed_to_date,
            t.invoice_count,
            t.last_invoice_date,
            t.deposit_billed,
            t.progress_billed,
            t.final_billed,
            t.deposit_count,
            t.progress_count,
            t.final_count,
            t.wip_to_date,
            t.allocated_months_count,
            t.allocation_sum_pct,
            t.allocation_sum_amount,
            t.locked_months_count,
            t.first_allocated_month,
            t.last_allocated_month,
            t.span_months,
            t.division_code,
            t.division_name,
            t.avg_wage,
            t.materials_pct,
            t.set_pct,
            t.billing_schedule_display,
            t.schedule_has_deposit,
            t.schedule_has_progress,
            t.schedule_has_wip_accrual,
            t.contract_sales_rate,
            t.co_sales_rate,
            t.total_hours,
            t.total_revenue,
            t.avg_labor_cost_per_hour,
            t.labor_cost_to_date,
            t.est_labor_cost_remaining,
            t.total_sales_rate,
            t.forecast_labor_cost_override,
            t.forecasted_materials_override,
            t.forecasted_set_override,
            round(COALESCE(t.forecast_labor_cost_override, COALESCE(t.total_hours, 0::numeric) * COALESCE(t.specialty_rate, t.avg_wage, 0::numeric)), 2) AS forecast_labor_cost,
            round(COALESCE(t.forecasted_materials_override, COALESCE(t.total_revenue, 0::numeric) * COALESCE(t.materials_pct, 0::numeric)), 2) AS forecasted_materials,
            round(COALESCE(t.forecasted_set_override, COALESCE(t.total_revenue, 0::numeric) * COALESCE(t.set_pct, 0::numeric)), 2) AS forecasted_set,
            round(COALESCE(t.labor_cost_to_date, 0::numeric) + COALESCE(t.material_cost_to_date, 0::numeric) + COALESCE(t.set_cost_to_date, 0::numeric), 2) AS total_cost_to_date,
            round(COALESCE(t.est_labor_cost_remaining, 0::numeric) + COALESCE(t.est_materials_remaining, 0::numeric) + COALESCE(t.est_set_remaining, 0::numeric), 2) AS est_total_remaining_cost
           FROM tier2 t
        ), tier2c AS (
         SELECT t.po_number,
            t.job_name,
            t.stage,
            t.tracking_mode,
            t.segment,
            t.sales_rep,
            t.team_leader,
            t.project_manager,
            t.job_site_address,
            t.city,
            t.state,
            t.zip_code,
            t.date_job_sold,
            t.estimated_start_date,
            t.duration_days,
            t.estimated_completion_date,
            t.company,
            t.customer,
            t.division_id,
            t.contract_hours,
            t.contract_revenue,
            t.co_hours,
            t.co_revenue,
            t.est_hours_remaining,
            t.est_materials_remaining,
            t.est_set_remaining,
            t.source_attribution,
            t.prev_or_new_customer,
            t.is_closed,
            t.closed_at,
            t.created_at,
            t.updated_at,
            t.hs_object_id,
            t.hubspot_url,
            t.specialty_rate,
            t.prev_wage_rate,
            t.billing_schedule_type,
            t.deposit_pct,
            t.deposit_amount,
            t.deposit_lead_days,
            t.billing_cadence,
            t.billing_notes,
            t.allocation_method,
            t.hours_to_date,
            t.ct_labor_cost_to_date,
            t.stored_labor_cost,
            t.material_cost_to_date,
            t.set_cost_to_date,
            t.amount_billed_to_date,
            t.invoice_count,
            t.last_invoice_date,
            t.deposit_billed,
            t.progress_billed,
            t.final_billed,
            t.deposit_count,
            t.progress_count,
            t.final_count,
            t.wip_to_date,
            t.allocated_months_count,
            t.allocation_sum_pct,
            t.allocation_sum_amount,
            t.locked_months_count,
            t.first_allocated_month,
            t.last_allocated_month,
            t.span_months,
            t.division_code,
            t.division_name,
            t.avg_wage,
            t.materials_pct,
            t.set_pct,
            t.billing_schedule_display,
            t.schedule_has_deposit,
            t.schedule_has_progress,
            t.schedule_has_wip_accrual,
            t.contract_sales_rate,
            t.co_sales_rate,
            t.total_hours,
            t.total_revenue,
            t.avg_labor_cost_per_hour,
            t.labor_cost_to_date,
            t.est_labor_cost_remaining,
            t.total_sales_rate,
            t.forecast_labor_cost_override,
            t.forecasted_materials_override,
            t.forecasted_set_override,
            t.forecast_labor_cost,
            t.forecasted_materials,
            t.forecasted_set,
            t.total_cost_to_date,
            t.est_total_remaining_cost,
            round(t.forecast_labor_cost + t.forecasted_materials + t.forecasted_set, 2) AS forecasted_cost_at_completion,
                CASE
                    WHEN t.stage = ANY (ARRAY['Need to Invoice'::text, 'Benchmark in Progress'::text, 'Benchmark Completed'::text]) THEN 'actuals_tracking'::character varying
                    WHEN t.est_total_remaining_cost = 0::numeric AND (t.total_cost_to_date + t.est_total_remaining_cost) < (t.forecast_labor_cost + t.forecasted_materials + t.forecasted_set) THEN 'forecast'::character varying
                    ELSE 'actuals_tracking'::character varying
                END AS computed_tracking_mode
           FROM tier2b t
        ), tier3 AS (
         SELECT t.po_number,
            t.job_name,
            t.stage,
            t.tracking_mode,
            t.segment,
            t.sales_rep,
            t.team_leader,
            t.project_manager,
            t.job_site_address,
            t.city,
            t.state,
            t.zip_code,
            t.date_job_sold,
            t.estimated_start_date,
            t.duration_days,
            t.estimated_completion_date,
            t.company,
            t.customer,
            t.division_id,
            t.contract_hours,
            t.contract_revenue,
            t.co_hours,
            t.co_revenue,
            t.est_hours_remaining,
            t.est_materials_remaining,
            t.est_set_remaining,
            t.source_attribution,
            t.prev_or_new_customer,
            t.is_closed,
            t.closed_at,
            t.created_at,
            t.updated_at,
            t.hs_object_id,
            t.hubspot_url,
            t.specialty_rate,
            t.prev_wage_rate,
            t.billing_schedule_type,
            t.deposit_pct,
            t.deposit_amount,
            t.deposit_lead_days,
            t.billing_cadence,
            t.billing_notes,
            t.allocation_method,
            t.hours_to_date,
            t.ct_labor_cost_to_date,
            t.stored_labor_cost,
            t.material_cost_to_date,
            t.set_cost_to_date,
            t.amount_billed_to_date,
            t.invoice_count,
            t.last_invoice_date,
            t.deposit_billed,
            t.progress_billed,
            t.final_billed,
            t.deposit_count,
            t.progress_count,
            t.final_count,
            t.wip_to_date,
            t.allocated_months_count,
            t.allocation_sum_pct,
            t.allocation_sum_amount,
            t.locked_months_count,
            t.first_allocated_month,
            t.last_allocated_month,
            t.span_months,
            t.division_code,
            t.division_name,
            t.avg_wage,
            t.materials_pct,
            t.set_pct,
            t.billing_schedule_display,
            t.schedule_has_deposit,
            t.schedule_has_progress,
            t.schedule_has_wip_accrual,
            t.contract_sales_rate,
            t.co_sales_rate,
            t.total_hours,
            t.total_revenue,
            t.avg_labor_cost_per_hour,
            t.labor_cost_to_date,
            t.est_labor_cost_remaining,
            t.total_sales_rate,
            t.forecast_labor_cost_override,
            t.forecasted_materials_override,
            t.forecasted_set_override,
            t.forecast_labor_cost,
            t.forecasted_materials,
            t.forecasted_set,
            t.total_cost_to_date,
            t.est_total_remaining_cost,
            t.forecasted_cost_at_completion,
            t.computed_tracking_mode,
                CASE
                    WHEN t.computed_tracking_mode::text = 'forecast'::text THEN t.total_hours
                    ELSE round(COALESCE(t.hours_to_date, 0::numeric) + COALESCE(t.est_hours_remaining, 0::numeric), 2)
                END AS total_project_hours,
                CASE
                    WHEN t.computed_tracking_mode::text = 'forecast'::text THEN t.forecast_labor_cost
                    ELSE round(COALESCE(t.labor_cost_to_date, 0::numeric) + COALESCE(t.est_labor_cost_remaining, 0::numeric), 2)
                END AS total_projected_labor_cost,
                CASE
                    WHEN t.computed_tracking_mode::text = 'forecast'::text THEN t.forecasted_materials
                    ELSE round(COALESCE(t.material_cost_to_date, 0::numeric) + COALESCE(t.est_materials_remaining, 0::numeric), 2)
                END AS total_projected_material_cost,
                CASE
                    WHEN t.computed_tracking_mode::text = 'forecast'::text THEN t.forecasted_set
                    ELSE round(COALESCE(t.set_cost_to_date, 0::numeric) + COALESCE(t.est_set_remaining, 0::numeric), 2)
                END AS total_projected_set_cost
           FROM tier2c t
        ), tier4 AS (
         SELECT t.po_number,
            t.job_name,
            t.stage,
            t.tracking_mode,
            t.segment,
            t.sales_rep,
            t.team_leader,
            t.project_manager,
            t.job_site_address,
            t.city,
            t.state,
            t.zip_code,
            t.date_job_sold,
            t.estimated_start_date,
            t.duration_days,
            t.estimated_completion_date,
            t.company,
            t.customer,
            t.division_id,
            t.contract_hours,
            t.contract_revenue,
            t.co_hours,
            t.co_revenue,
            t.est_hours_remaining,
            t.est_materials_remaining,
            t.est_set_remaining,
            t.source_attribution,
            t.prev_or_new_customer,
            t.is_closed,
            t.closed_at,
            t.created_at,
            t.updated_at,
            t.hs_object_id,
            t.hubspot_url,
            t.specialty_rate,
            t.prev_wage_rate,
            t.billing_schedule_type,
            t.deposit_pct,
            t.deposit_amount,
            t.deposit_lead_days,
            t.billing_cadence,
            t.billing_notes,
            t.allocation_method,
            t.hours_to_date,
            t.ct_labor_cost_to_date,
            t.stored_labor_cost,
            t.material_cost_to_date,
            t.set_cost_to_date,
            t.amount_billed_to_date,
            t.invoice_count,
            t.last_invoice_date,
            t.deposit_billed,
            t.progress_billed,
            t.final_billed,
            t.deposit_count,
            t.progress_count,
            t.final_count,
            t.wip_to_date,
            t.allocated_months_count,
            t.allocation_sum_pct,
            t.allocation_sum_amount,
            t.locked_months_count,
            t.first_allocated_month,
            t.last_allocated_month,
            t.span_months,
            t.division_code,
            t.division_name,
            t.avg_wage,
            t.materials_pct,
            t.set_pct,
            t.billing_schedule_display,
            t.schedule_has_deposit,
            t.schedule_has_progress,
            t.schedule_has_wip_accrual,
            t.contract_sales_rate,
            t.co_sales_rate,
            t.total_hours,
            t.total_revenue,
            t.avg_labor_cost_per_hour,
            t.labor_cost_to_date,
            t.est_labor_cost_remaining,
            t.total_sales_rate,
            t.forecast_labor_cost_override,
            t.forecasted_materials_override,
            t.forecasted_set_override,
            t.forecast_labor_cost,
            t.forecasted_materials,
            t.forecasted_set,
            t.total_cost_to_date,
            t.est_total_remaining_cost,
            t.forecasted_cost_at_completion,
            t.computed_tracking_mode,
            t.total_project_hours,
            t.total_projected_labor_cost,
            t.total_projected_material_cost,
            t.total_projected_set_cost,
            round(t.total_projected_labor_cost + t.total_projected_material_cost + t.total_projected_set_cost, 2) AS total_projected_cost
           FROM tier3 t
        ), tier5 AS (
         SELECT t.po_number,
            t.job_name,
            t.stage,
            t.tracking_mode,
            t.segment,
            t.sales_rep,
            t.team_leader,
            t.project_manager,
            t.job_site_address,
            t.city,
            t.state,
            t.zip_code,
            t.date_job_sold,
            t.estimated_start_date,
            t.duration_days,
            t.estimated_completion_date,
            t.company,
            t.customer,
            t.division_id,
            t.contract_hours,
            t.contract_revenue,
            t.co_hours,
            t.co_revenue,
            t.est_hours_remaining,
            t.est_materials_remaining,
            t.est_set_remaining,
            t.source_attribution,
            t.prev_or_new_customer,
            t.is_closed,
            t.closed_at,
            t.created_at,
            t.updated_at,
            t.hs_object_id,
            t.hubspot_url,
            t.specialty_rate,
            t.prev_wage_rate,
            t.billing_schedule_type,
            t.deposit_pct,
            t.deposit_amount,
            t.deposit_lead_days,
            t.billing_cadence,
            t.billing_notes,
            t.allocation_method,
            t.hours_to_date,
            t.ct_labor_cost_to_date,
            t.stored_labor_cost,
            t.material_cost_to_date,
            t.set_cost_to_date,
            t.amount_billed_to_date,
            t.invoice_count,
            t.last_invoice_date,
            t.deposit_billed,
            t.progress_billed,
            t.final_billed,
            t.deposit_count,
            t.progress_count,
            t.final_count,
            t.wip_to_date,
            t.allocated_months_count,
            t.allocation_sum_pct,
            t.allocation_sum_amount,
            t.locked_months_count,
            t.first_allocated_month,
            t.last_allocated_month,
            t.span_months,
            t.division_code,
            t.division_name,
            t.avg_wage,
            t.materials_pct,
            t.set_pct,
            t.billing_schedule_display,
            t.schedule_has_deposit,
            t.schedule_has_progress,
            t.schedule_has_wip_accrual,
            t.contract_sales_rate,
            t.co_sales_rate,
            t.total_hours,
            t.total_revenue,
            t.avg_labor_cost_per_hour,
            t.labor_cost_to_date,
            t.est_labor_cost_remaining,
            t.total_sales_rate,
            t.forecast_labor_cost_override,
            t.forecasted_materials_override,
            t.forecasted_set_override,
            t.forecast_labor_cost,
            t.forecasted_materials,
            t.forecasted_set,
            t.total_cost_to_date,
            t.est_total_remaining_cost,
            t.forecasted_cost_at_completion,
            t.computed_tracking_mode,
            t.total_project_hours,
            t.total_projected_labor_cost,
            t.total_projected_material_cost,
            t.total_projected_set_cost,
            t.total_projected_cost,
            round(t.total_revenue - t.total_projected_cost, 2) AS est_gross_profit,
            round(t.total_revenue - t.forecasted_cost_at_completion, 2) AS forecasted_gp,
                CASE
                    WHEN t.stage = ANY (ARRAY['Need to Invoice'::text, 'Benchmark in Progress'::text, 'Benchmark Completed'::text]) THEN 1.0
                    ELSE round(t.total_cost_to_date / NULLIF(t.total_projected_cost, 0::numeric), 4)
                END AS pct_complete
           FROM tier4 t
        ), tier6 AS (
         SELECT t.po_number,
            t.job_name,
            t.stage,
            t.tracking_mode,
            t.segment,
            t.sales_rep,
            t.team_leader,
            t.project_manager,
            t.job_site_address,
            t.city,
            t.state,
            t.zip_code,
            t.date_job_sold,
            t.estimated_start_date,
            t.duration_days,
            t.estimated_completion_date,
            t.company,
            t.customer,
            t.division_id,
            t.contract_hours,
            t.contract_revenue,
            t.co_hours,
            t.co_revenue,
            t.est_hours_remaining,
            t.est_materials_remaining,
            t.est_set_remaining,
            t.source_attribution,
            t.prev_or_new_customer,
            t.is_closed,
            t.closed_at,
            t.created_at,
            t.updated_at,
            t.hs_object_id,
            t.hubspot_url,
            t.specialty_rate,
            t.prev_wage_rate,
            t.billing_schedule_type,
            t.deposit_pct,
            t.deposit_amount,
            t.deposit_lead_days,
            t.billing_cadence,
            t.billing_notes,
            t.allocation_method,
            t.hours_to_date,
            t.ct_labor_cost_to_date,
            t.stored_labor_cost,
            t.material_cost_to_date,
            t.set_cost_to_date,
            t.amount_billed_to_date,
            t.invoice_count,
            t.last_invoice_date,
            t.deposit_billed,
            t.progress_billed,
            t.final_billed,
            t.deposit_count,
            t.progress_count,
            t.final_count,
            t.wip_to_date,
            t.allocated_months_count,
            t.allocation_sum_pct,
            t.allocation_sum_amount,
            t.locked_months_count,
            t.first_allocated_month,
            t.last_allocated_month,
            t.span_months,
            t.division_code,
            t.division_name,
            t.avg_wage,
            t.materials_pct,
            t.set_pct,
            t.billing_schedule_display,
            t.schedule_has_deposit,
            t.schedule_has_progress,
            t.schedule_has_wip_accrual,
            t.contract_sales_rate,
            t.co_sales_rate,
            t.total_hours,
            t.total_revenue,
            t.avg_labor_cost_per_hour,
            t.labor_cost_to_date,
            t.est_labor_cost_remaining,
            t.total_sales_rate,
            t.forecast_labor_cost_override,
            t.forecasted_materials_override,
            t.forecasted_set_override,
            t.forecast_labor_cost,
            t.forecasted_materials,
            t.forecasted_set,
            t.total_cost_to_date,
            t.est_total_remaining_cost,
            t.forecasted_cost_at_completion,
            t.computed_tracking_mode,
            t.total_project_hours,
            t.total_projected_labor_cost,
            t.total_projected_material_cost,
            t.total_projected_set_cost,
            t.total_projected_cost,
            t.est_gross_profit,
            t.forecasted_gp,
            t.pct_complete,
            round(t.est_gross_profit / NULLIF(t.total_revenue, 0::numeric), 4) AS est_gp_pct,
                CASE
                    WHEN t.computed_tracking_mode::text = 'forecast'::text THEN round(t.est_gross_profit / NULLIF(t.total_hours, 0::numeric), 2)
                    ELSE round(t.est_gross_profit / NULLIF(t.total_project_hours, 0::numeric), 2)
                END AS est_gp_per_hour,
            round(t.forecasted_gp / NULLIF(t.total_revenue, 0::numeric), 4) AS forecasted_gp_pct,
            round(t.forecasted_gp / NULLIF(t.total_hours, 0::numeric), 2) AS forecasted_gp_per_hour,
            round(t.total_revenue / NULLIF(t.total_project_hours, 0::numeric), 2) AS realized_sales_rate,
            round(t.total_projected_labor_cost / NULLIF(t.total_revenue, 0::numeric), 4) AS labor_pct_of_revenue,
            round(t.total_projected_material_cost / NULLIF(t.total_revenue, 0::numeric), 4) AS material_pct_of_revenue,
            round(t.total_projected_set_cost / NULLIF(t.total_revenue, 0::numeric), 4) AS set_pct_of_revenue,
            round(t.pct_complete * t.total_revenue, 2) AS revenue_earned
           FROM tier5 t
        ), tier7 AS (
         SELECT t.po_number,
            t.job_name,
            t.stage,
            t.tracking_mode,
            t.segment,
            t.sales_rep,
            t.team_leader,
            t.project_manager,
            t.job_site_address,
            t.city,
            t.state,
            t.zip_code,
            t.date_job_sold,
            t.estimated_start_date,
            t.duration_days,
            t.estimated_completion_date,
            t.company,
            t.customer,
            t.division_id,
            t.contract_hours,
            t.contract_revenue,
            t.co_hours,
            t.co_revenue,
            t.est_hours_remaining,
            t.est_materials_remaining,
            t.est_set_remaining,
            t.source_attribution,
            t.prev_or_new_customer,
            t.is_closed,
            t.closed_at,
            t.created_at,
            t.updated_at,
            t.hs_object_id,
            t.hubspot_url,
            t.specialty_rate,
            t.prev_wage_rate,
            t.billing_schedule_type,
            t.deposit_pct,
            t.deposit_amount,
            t.deposit_lead_days,
            t.billing_cadence,
            t.billing_notes,
            t.allocation_method,
            t.hours_to_date,
            t.ct_labor_cost_to_date,
            t.stored_labor_cost,
            t.material_cost_to_date,
            t.set_cost_to_date,
            t.amount_billed_to_date,
            t.invoice_count,
            t.last_invoice_date,
            t.deposit_billed,
            t.progress_billed,
            t.final_billed,
            t.deposit_count,
            t.progress_count,
            t.final_count,
            t.wip_to_date,
            t.allocated_months_count,
            t.allocation_sum_pct,
            t.allocation_sum_amount,
            t.locked_months_count,
            t.first_allocated_month,
            t.last_allocated_month,
            t.span_months,
            t.division_code,
            t.division_name,
            t.avg_wage,
            t.materials_pct,
            t.set_pct,
            t.billing_schedule_display,
            t.schedule_has_deposit,
            t.schedule_has_progress,
            t.schedule_has_wip_accrual,
            t.contract_sales_rate,
            t.co_sales_rate,
            t.total_hours,
            t.total_revenue,
            t.avg_labor_cost_per_hour,
            t.labor_cost_to_date,
            t.est_labor_cost_remaining,
            t.total_sales_rate,
            t.forecast_labor_cost_override,
            t.forecasted_materials_override,
            t.forecasted_set_override,
            t.forecast_labor_cost,
            t.forecasted_materials,
            t.forecasted_set,
            t.total_cost_to_date,
            t.est_total_remaining_cost,
            t.forecasted_cost_at_completion,
            t.computed_tracking_mode,
            t.total_project_hours,
            t.total_projected_labor_cost,
            t.total_projected_material_cost,
            t.total_projected_set_cost,
            t.total_projected_cost,
            t.est_gross_profit,
            t.forecasted_gp,
            t.pct_complete,
            t.est_gp_pct,
            t.est_gp_per_hour,
            t.forecasted_gp_pct,
            t.forecasted_gp_per_hour,
            t.realized_sales_rate,
            t.labor_pct_of_revenue,
            t.material_pct_of_revenue,
            t.set_pct_of_revenue,
            t.revenue_earned,
                CASE
                    WHEN t.revenue_earned > COALESCE(t.amount_billed_to_date, 0::numeric) THEN round(t.revenue_earned - COALESCE(t.amount_billed_to_date, 0::numeric), 2)
                    ELSE 0::numeric
                END AS unbilled_revenue_calc,
                CASE
                    WHEN t.revenue_earned > (COALESCE(t.amount_billed_to_date, 0::numeric) + COALESCE(t.wip_to_date, 0::numeric)) THEN round(t.revenue_earned - (COALESCE(t.amount_billed_to_date, 0::numeric) + COALESCE(t.wip_to_date, 0::numeric)), 2)
                    ELSE 0::numeric
                END AS costs_in_excess_of_billings_calc,
                CASE
                    WHEN COALESCE(t.amount_billed_to_date, 0::numeric) > t.revenue_earned THEN round(COALESCE(t.amount_billed_to_date, 0::numeric) - t.revenue_earned, 2)
                    ELSE 0::numeric
                END AS billings_in_excess_of_costs_calc,
            round(COALESCE(t.amount_billed_to_date, 0::numeric) + COALESCE(t.wip_to_date, 0::numeric), 2) AS amount_claimed_to_date_calc,
                CASE
                    WHEN t.last_invoice_date IS NOT NULL THEN CURRENT_DATE - t.last_invoice_date
                    ELSE NULL::integer
                END AS days_since_last_invoice,
                CASE
                    WHEN t.allocated_months_count = 0 THEN false
                    WHEN abs(t.allocation_sum_pct - 1.0) <= 0.001 THEN true
                    ELSE false
                END AS is_allocation_complete,
                CASE
                    WHEN t.allocated_months_count = 0 THEN NULL::text
                    WHEN t.allocated_months_count = 1 THEN 'single_month'::text
                    WHEN t.allocated_months_count = 2 AND t.span_months = 2 THEN 'two_month'::text
                    WHEN t.allocated_months_count = t.span_months THEN 'multi_month_sequential'::text
                    ELSE 'multi_month_non_sequential'::text
                END AS allocation_pattern_derived
           FROM tier6 t
        ), tier8 AS (
         SELECT t.po_number,
            t.job_name,
            t.stage,
            t.tracking_mode,
            t.segment,
            t.sales_rep,
            t.team_leader,
            t.project_manager,
            t.job_site_address,
            t.city,
            t.state,
            t.zip_code,
            t.date_job_sold,
            t.estimated_start_date,
            t.duration_days,
            t.estimated_completion_date,
            t.company,
            t.customer,
            t.division_id,
            t.contract_hours,
            t.contract_revenue,
            t.co_hours,
            t.co_revenue,
            t.est_hours_remaining,
            t.est_materials_remaining,
            t.est_set_remaining,
            t.source_attribution,
            t.prev_or_new_customer,
            t.is_closed,
            t.closed_at,
            t.created_at,
            t.updated_at,
            t.hs_object_id,
            t.hubspot_url,
            t.specialty_rate,
            t.prev_wage_rate,
            t.billing_schedule_type,
            t.deposit_pct,
            t.deposit_amount,
            t.deposit_lead_days,
            t.billing_cadence,
            t.billing_notes,
            t.allocation_method,
            t.hours_to_date,
            t.ct_labor_cost_to_date,
            t.stored_labor_cost,
            t.material_cost_to_date,
            t.set_cost_to_date,
            t.amount_billed_to_date,
            t.invoice_count,
            t.last_invoice_date,
            t.deposit_billed,
            t.progress_billed,
            t.final_billed,
            t.deposit_count,
            t.progress_count,
            t.final_count,
            t.wip_to_date,
            t.allocated_months_count,
            t.allocation_sum_pct,
            t.allocation_sum_amount,
            t.locked_months_count,
            t.first_allocated_month,
            t.last_allocated_month,
            t.span_months,
            t.division_code,
            t.division_name,
            t.avg_wage,
            t.materials_pct,
            t.set_pct,
            t.billing_schedule_display,
            t.schedule_has_deposit,
            t.schedule_has_progress,
            t.schedule_has_wip_accrual,
            t.contract_sales_rate,
            t.co_sales_rate,
            t.total_hours,
            t.total_revenue,
            t.avg_labor_cost_per_hour,
            t.labor_cost_to_date,
            t.est_labor_cost_remaining,
            t.total_sales_rate,
            t.forecast_labor_cost_override,
            t.forecasted_materials_override,
            t.forecasted_set_override,
            t.forecast_labor_cost,
            t.forecasted_materials,
            t.forecasted_set,
            t.total_cost_to_date,
            t.est_total_remaining_cost,
            t.forecasted_cost_at_completion,
            t.computed_tracking_mode,
            t.total_project_hours,
            t.total_projected_labor_cost,
            t.total_projected_material_cost,
            t.total_projected_set_cost,
            t.total_projected_cost,
            t.est_gross_profit,
            t.forecasted_gp,
            t.pct_complete,
            t.est_gp_pct,
            t.est_gp_per_hour,
            t.forecasted_gp_pct,
            t.forecasted_gp_per_hour,
            t.realized_sales_rate,
            t.labor_pct_of_revenue,
            t.material_pct_of_revenue,
            t.set_pct_of_revenue,
            t.revenue_earned,
            t.unbilled_revenue_calc,
            t.costs_in_excess_of_billings_calc,
            t.billings_in_excess_of_costs_calc,
            t.amount_claimed_to_date_calc,
            t.days_since_last_invoice,
            t.is_allocation_complete,
            t.allocation_pattern_derived,
                CASE
                    WHEN t.billing_schedule_type IS NULL THEN NULL::text
                    WHEN t.is_closed THEN NULL::text
                    WHEN t.billing_schedule_type = 'single_final'::text THEN
                    CASE
                        WHEN t.final_count = 0 THEN 'Final'::text
                        ELSE NULL::text
                    END
                    WHEN t.billing_schedule_type = 'deposit_final'::text THEN
                    CASE
                        WHEN t.deposit_count = 0 THEN 'Deposit'::text
                        WHEN t.final_count = 0 THEN 'Final'::text
                        ELSE NULL::text
                    END
                    WHEN t.billing_schedule_type = 'deposit_progress'::text THEN
                    CASE
                        WHEN t.deposit_count = 0 THEN 'Deposit'::text
                        WHEN t.stage = ANY (ARRAY['Need to Invoice'::text, 'Benchmark in Progress'::text, 'Benchmark Completed'::text]) THEN 'Final'::text
                        ELSE 'Progress'::text
                    END
                    WHEN t.billing_schedule_type = 'progress_only'::text THEN
                    CASE
                        WHEN t.stage = ANY (ARRAY['Need to Invoice'::text, 'Benchmark in Progress'::text, 'Benchmark Completed'::text]) THEN 'Final'::text
                        ELSE 'Progress'::text
                    END
                    WHEN t.billing_schedule_type = 'wip_then_final'::text THEN
                    CASE
                        WHEN t.final_count = 0 THEN 'Final'::text
                        ELSE NULL::text
                    END
                    WHEN t.billing_schedule_type = 'wip_then_progress'::text THEN
                    CASE
                        WHEN t.stage = ANY (ARRAY['Need to Invoice'::text, 'Benchmark in Progress'::text, 'Benchmark Completed'::text]) THEN 'Final'::text
                        ELSE 'Progress'::text
                    END
                    ELSE NULL::text
                END AS expected_next_invoice_type,
                CASE
                    WHEN t.schedule_has_wip_accrual = true AND t.costs_in_excess_of_billings_calc > 0::numeric AND t.is_closed = false THEN true
                    ELSE false
                END AS wip_eligible,
                CASE
                    WHEN t.is_closed THEN 'closed'::text
                    WHEN t.billing_schedule_type IS NULL THEN 'unassigned'::text
                    WHEN t.billings_in_excess_of_costs_calc > 0::numeric THEN 'overbilled'::text
                    WHEN t.schedule_has_deposit = true AND t.deposit_count = 0 THEN 'awaiting_deposit'::text
                    WHEN (t.stage = ANY (ARRAY['Need to Invoice'::text, 'Benchmark in Progress'::text, 'Benchmark Completed'::text])) AND t.final_count = 0 THEN 'awaiting_final'::text
                    WHEN t.unbilled_revenue_calc > 0::numeric THEN 'behind'::text
                    ELSE 'on_track'::text
                END AS billing_status
           FROM tier7 t
        )
 SELECT po_number,
    job_name,
    stage,
    computed_tracking_mode AS tracking_mode,
    segment,
    sales_rep,
    team_leader,
    project_manager,
    estimated_start_date,
    duration_days,
    estimated_completion_date,
    total_hours,
    total_revenue,
    total_sales_rate,
    contract_hours,
    contract_revenue,
    contract_sales_rate,
    co_hours,
    co_revenue,
    co_sales_rate,
    hours_to_date,
    est_hours_remaining,
    total_project_hours,
        CASE
            WHEN computed_tracking_mode::text = 'forecast'::text THEN 1.0
            ELSE round(total_hours / NULLIF(total_project_hours, 0::numeric), 2)
        END AS productivity,
    avg_labor_cost_per_hour,
    ct_labor_cost_to_date,
    labor_cost_to_date,
    est_labor_cost_remaining,
    material_cost_to_date,
    est_materials_remaining,
    set_cost_to_date,
    est_set_remaining,
    total_cost_to_date,
    est_total_remaining_cost,
    total_projected_labor_cost,
    labor_pct_of_revenue,
    total_projected_material_cost,
    material_pct_of_revenue,
    total_projected_set_cost,
    set_pct_of_revenue,
    forecast_labor_cost,
    forecasted_materials,
    forecasted_set,
    forecasted_cost_at_completion,
    total_projected_cost,
    est_gross_profit,
    est_gp_pct,
    est_gp_per_hour,
    forecasted_gp,
    forecasted_gp_pct,
    forecasted_gp_per_hour,
    realized_sales_rate,
    round(realized_sales_rate - total_sales_rate, 2) AS sales_rate_variance,
    amount_billed_to_date,
    wip_to_date,
    amount_claimed_to_date_calc AS amount_claimed_to_date,
    pct_complete,
    revenue_earned,
    unbilled_revenue_calc AS unbilled_revenue,
    costs_in_excess_of_billings_calc AS costs_in_excess_of_billings,
    billings_in_excess_of_costs_calc AS billings_in_excess_of_costs,
    billing_schedule_type,
    billing_schedule_display,
    schedule_has_deposit,
    schedule_has_progress,
    schedule_has_wip_accrual,
    deposit_pct,
    deposit_amount,
    deposit_lead_days,
    billing_cadence,
    billing_notes,
    deposit_billed,
    progress_billed,
    final_billed,
    deposit_count,
    progress_count,
    final_count,
    invoice_count,
    last_invoice_date,
    days_since_last_invoice,
    expected_next_invoice_type,
    wip_eligible,
    billing_status,
    allocation_method,
    allocation_pattern_derived AS allocation_pattern,
    allocated_months_count,
    locked_months_count,
    allocation_sum_pct,
    allocation_sum_amount,
    is_allocation_complete,
    first_allocated_month,
    last_allocated_month,
    span_months AS allocation_span_months,
    date_job_sold,
    company,
    customer,
    job_site_address,
    city,
    state,
    zip_code,
    source_attribution,
    prev_or_new_customer,
    specialty_rate,
    prev_wage_rate,
    division_id,
    division_code,
    division_name,
    avg_wage,
    materials_pct,
    set_pct,
    hs_object_id,
    hubspot_url,
    is_closed,
    closed_at,
    created_at,
    updated_at,
    forecast_labor_cost_override,
    forecasted_materials_override,
    forecasted_set_override
   FROM tier8;
