import { fmtCurrency, fmtPct } from './formatters'

export const costColumns = [
  {
    id: 'labor_cost_to_date',
    accessorKey: 'labor_cost_to_date',
    header: 'Labor Cost',
    size: 120,
    cell: ({ getValue }) => <span className="font-mono">{fmtCurrency(getValue())}</span>,
  },
  {
    id: 'material_cost_to_date',
    accessorKey: 'material_cost_to_date',
    header: 'Material Cost',
    size: 120,
    cell: ({ getValue }) => <span className="font-mono">{fmtCurrency(getValue())}</span>,
  },
  {
    id: 'set_cost_to_date',
    accessorKey: 'set_cost_to_date',
    header: 'SET Cost',
    size: 110,
    cell: ({ getValue }) => <span className="font-mono">{fmtCurrency(getValue())}</span>,
  },
  {
    id: 'total_cost_to_date',
    accessorKey: 'total_cost_to_date',
    header: 'Total Cost',
    size: 120,
    cell: ({ getValue }) => <span className="font-mono">{fmtCurrency(getValue())}</span>,
  },
  {
    id: 'est_cost_at_completion',
    accessorKey: 'est_cost_at_completion',
    header: 'Est Cost at Close',
    size: 140,
    cell: ({ getValue }) => <span className="font-mono">{fmtCurrency(getValue())}</span>,
  },
  {
    id: 'labor_pct_of_revenue',
    accessorKey: 'labor_pct_of_revenue',
    header: 'Labor %',
    size: 90,
    cell: ({ getValue }) => <span className="font-mono">{fmtPct(getValue())}</span>,
  },
  {
    id: 'material_pct_of_revenue',
    accessorKey: 'material_pct_of_revenue',
    header: 'Material %',
    size: 100,
    cell: ({ getValue }) => <span className="font-mono">{fmtPct(getValue())}</span>,
  },
  {
    id: 'avg_labor_cost_per_hour',
    accessorKey: 'avg_labor_cost_per_hour',
    header: 'Avg Labor $/hr',
    size: 130,
    cell: ({ getValue }) => <span className="font-mono">{fmtCurrency(getValue())}</span>,
  },
  {
    id: 'est_labor_cost_remaining',
    accessorKey: 'est_labor_cost_remaining',
    header: 'Est Labor Remaining',
    size: 160,
    cell: ({ getValue }) => <span className="font-mono">{fmtCurrency(getValue())}</span>,
  },
  {
    id: 'est_materials_remaining',
    accessorKey: 'est_materials_remaining',
    header: 'Est Materials Remaining',
    size: 170,
    meta: { editable: true, inputType: 'number' },
    cell: ({ getValue }) => <span className="font-mono">{fmtCurrency(getValue())}</span>,
  },
  {
    id: 'est_set_remaining',
    accessorKey: 'est_set_remaining',
    header: 'Est SET Remaining',
    size: 150,
    meta: { editable: true, inputType: 'number' },
    cell: ({ getValue }) => <span className="font-mono">{fmtCurrency(getValue())}</span>,
  },
  {
    id: 'est_total_remaining_cost',
    accessorKey: 'est_total_remaining_cost',
    header: 'Est Total Remaining',
    size: 160,
    cell: ({ getValue }) => <span className="font-mono">{fmtCurrency(getValue())}</span>,
  },
]
